services:
  - type: web
    name: magma-backend
    env: node
    plan: free
    rootDir: node-backend
    buildCommand: "npm install && cd ../react-frontend && npm install && npm run build"
    startCommand: "node server.js"

