services:
  - type: web
    name: magma-backend
    env: node
    plan: free
    rootDir: node-backend
    buildCommand: "cd ../react-frontend && npm install && npm run build && cd ../node-backend && npm install"
    startCommand: "node server.js"

