services:
  - type: web
    name: magma-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: "npm install && cd node-backend && npm install && cd ../react-frontend && npm install && npm run build"
    startCommand: "node server.js"

