services:
  - type: web
    name: magma-backend
    env: node
    plan: free
    buildCommand: "cd react-frontend && npm install && npm run build && cd ../node-backend && npm install"
    startCommand: "node node-backend/server.js"

